<option value="DGI">DGI</option>
<option value="BPS">BPS</option>
<option value="BPS-DGI">BPS-DGI</option>
<option value="EMPRESA EN EL DÍA">EMPRESA EN EL DÍA</option>
<option value="MTSS">MTSS</option>
<option value="MGAP">MGAP</option>
<option value="IMM">IMM</option>
<option value="ABITAB">ABITAB</option>
<option value="COCER">COCER</option>
<option value="BSE">BSE</option>
<option value="CBH">CBH</option>
<option value="BROU">BROU</option>
<option value="BANCO SANTANDER">BANCO SANTANDER</option>
<option value="ROZEMBLUM Y ASOC.">ROZEMBLUM Y ASOC.</option>
<option value="LA ECONÓMICA SA">LA ECONÓMICA SA</option>
<option value="CATASTRO">CATASTRO</option>
<option value="IMPRENTA LA HOJA">IMPRENTA LA HOJA</option>
<option value="IMPRENTA CALYFA">IMPRENTA CALYFA</option>
<option value="DR. MAZZA">DR. MAZZA</option>
<option value="IPNL SRL">IPNL SRL</option>
<option value="MACHADO">MACHADO</option>
<option value="DRA. PESCETTO">DRA. PESCETTO</option>
<option value="OTRO">OTRO</option>
